spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/caizhijian?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456


mybatis:
  configuration:
    map-underscore-to-camel-case: true